version: '3.8'

services:
  ksamti-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      # En caso de querer persistir logs (opcional)
      - ./logs:/app/logs

  # Base de datos (para futuro uso)
  # database:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: ksamti
  #     POSTGRES_USER: ksamti_user
  #     POSTGRES_PASSWORD: ksamti_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:

